In [1]:
file_path = 'enron1/ham/0007.1999-12-14.farmer.ham.txt'

In [2]:
with open(file_path, 'r') as infile:
    ham_sample = infile.read()

In [3]:
print(ham_sample)

Subject: mcmullen gas for 11 / 99
jackie ,
since the inlet to 3 river plant is shut in on 10 / 19 / 99 ( the last day of
flow ) :
at what meter is the mcmullen gas being diverted to ?
at what meter is hpl buying the residue gas ? ( this is the gas from teco ,
vastar , vintage , tejones , and swift )
i still see active deals at meter 3405 in path manager for teco , vastar ,
vintage , tejones , and swift
i also see gas scheduled in pops at meter 3404 and 3405 .
please advice . we need to resolve this as soon as possible so settlement
can send out payments .
thanks


In [4]:
file_path = 'enron1/spam/0058.2003-12-21.GP.spam.txt'

In [5]:
with open(file_path, 'r') as infile:
    spam_sample = infile.read()

In [6]:
print(spam_sample)

Subject: stacey automated system generating 8 k per week parallelogram
people are
getting rich using this system ! now it ' s your
turn !
we ' ve
cracked the code and will show you . . . .
this is the
only system that does everything for you , so you can make
money
. . . . . . . .
because your
success is . . . completely automated !
let me show
you how !
click
here
to opt out click here % random _ text



In [7]:
import glob
import os

In [8]:
emails, labels = [], []

In [9]:
file_path = 'enron1/spam'

In [10]:
for filename in glob.glob(os.path.join(file_path, '*.txt')):
    with open(filename, 'r', encoding = 'ISO-8859-1') as infile:
        emails.append(infile.read())
        labels.append(0)

In [11]:
len(emails)

1500

In [12]:
len(labels)

1500

In [13]:
from nltk.corpus import names
from nltk.stem import WordNetLemmatizer
import nltk

In [14]:
def letters_only(astr):
    return astr.isalpha()

In [15]:
nltk.download('names')
nltk.download('wordnet')
all_names = set(names.words())

[nltk_data] Downloading package names to /home/codespace/nltk_data...
[nltk_data]   Package names is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /home/codespace/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [16]:
lemmatizer = WordNetLemmatizer()

In [17]:
def clean_text(docs):
    cleaned_docs = []
    for doc in docs:
        cleaned_docs.append(' '.join([lemmatizer.lemmatize(word.lower()) 
                                      for word in doc.split() 
                                      if letters_only(word) 
                                      and word not in all_names]))
    return cleaned_docs

In [18]:
cleaned_emails = clean_text(emails)

In [19]:
cleaned_emails[0]

'fw don t be a fuddy duddy use the sof tware everyone s using oemwhat is it oem stand for original equipment manufacturer it primarily refers to name brand software that come without the box or owner s manual this isn t a problem because of the time one can find the manual to download right online from the manufacturer website why do you care you can purchase oemincluding microsoft microsoft office adobe macromedia corel even title for the macintosh for unbelievably low price afraction of what it costsfrom the original manufacturer you need to see it to bel ieve it you candownload it straight from this siteby going here keep in mind you ll need to burnthe isoto a cd if you don t have a cd burneryou can go hereand have themmail it rightto your doorstep at no extra cost cancel auto update follow this one'

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

In [21]:
cv = CountVectorizer(stop_words = 'english', max_features = 500)

In [22]:
term_docs = cv.fit_transform(cleaned_emails)

In [23]:
print(term_docs.shape)

(1500, 500)


In [24]:
print(len(cleaned_emails))

1500


In [25]:
feature_names = cv.get_feature_names_out()

In [26]:
feature_names[60]

'colspan'

In [27]:
feature_mapping = cv.vocabulary_

In [28]:
def get_label_index(labels):
    from collections import defaultdict
    label_index = defaultdict(list)
    for index, label in enumerate(labels):
        label_index[label].append(index)
    return label_index
label_index = get_label_index(labels)

In [29]:
def get_prior(label_index):
    """Compute prior based on training samples
    Args:
        label_index (grouped sample infices by class)
    Returns:
        dictionary, with class label as key, corresponding
        prior as the value
    """

    prior = {label: len(index) for label, index in label_index.items()}
    total_count = sum(prior.values())
    for label in prior:
        prior[label] /= float(total_count)
    return prior

In [30]:
prior = get_prior(label_index)

In [31]:
prior

{0: 1.0}

In [32]:
import numpy as np

In [33]:
def get_likelihood(term_docs, label_index, smoothing = 0):
    """Compute likelihood based on training samples
    Args:
        term_docs (sparse matrix)
        label_index (grouped sample infices by class)
        smoothing (integer, additive Laplace smoothing parameter)
    Returns:
        dictionary, with class label as key, corresponding
        conditional probability P(feature|class) vector as the value
    """
    likelihood = {}
    for label, index in label_index.items():
        likelihood[label] = term_docs[index, :].sum(axis = 0) + smoothing
        likelihood[label] = np.asarray(likelihood[label])[0]
        total_count = likelihood[label].sum()
        likelihood[label] = likelihood[label] / float(total_count)
    return likelihood

In [34]:
smoothing = 1

In [35]:
likelihood = get_likelihood(term_docs, label_index, smoothing)

In [36]:
len(likelihood[0])

500

In [37]:
likelihood[0][:5]

array([0.00085199, 0.0011092 , 0.00356873, 0.00329545, 0.00181652])

In [38]:
likelihood

{0: array([0.00085199, 0.0011092 , 0.00356873, 0.00329545, 0.00181652,
        0.0009163 , 0.00107705, 0.00286141, 0.00268459, 0.00258813,
        0.00085199, 0.00099667, 0.00102882, 0.00147893, 0.00376163,
        0.00085199, 0.00114135, 0.00128603, 0.00106097, 0.00133425,
        0.00085199, 0.0009163 , 0.00308647, 0.00152716, 0.00249168,
        0.00143071, 0.00149501, 0.00083592, 0.00409922, 0.00143071,
        0.00170399, 0.00149501, 0.00141463, 0.00316685, 0.00102882,
        0.00286141, 0.00157539, 0.00128603, 0.00472616, 0.0021541 ,
        0.00143071, 0.00114135, 0.0009163 , 0.00141463, 0.00143071,
        0.00266851, 0.00245953, 0.00112528, 0.00088414, 0.00157539,
        0.00112528, 0.00128603, 0.00163969, 0.00086807, 0.00168791,
        0.00245953, 0.0012378 , 0.00149501, 0.00414744, 0.00329545,
        0.00109312, 0.01597891, 0.00194512, 0.00106097, 0.0009806 ,
        0.01482148, 0.00085199, 0.00128603, 0.00151108, 0.00390631,
        0.0011092 , 0.00395454, 0.00085199, 0

In [39]:
feature_names[:5]

array(['able', 'access', 'account', 'act', 'action'], dtype=object)

In [40]:
def get_posterior(term_docs, prior, likelihood):
    """Compute posterior of testing samples, based on prior and likelihood
    Args:
        term_docs (sparse matrix)
        prior (dictionary, with class label as key, corresponding
               prior as the value)
        likelihood (dictionary, with class label as key, corresponding
                    conditional probability P(feature|class) vector as the value)
    Returns:
        dictionary, with class label as key, corresponding
        posterior probability P(class|feature) vector as the value
    """
    num_docs = term_docs.shape[0]
    posteriors = []

    for i in range (num_docs):
        # posterior is proportional to prior * likelihood
        # = exp(log(prior * likelihood))
        # = exp(log(prior) + log(likelihood))
        
        posterior = {key: np.log(prior_label) 
        for key, prior_label in prior.items()}

        for label, likelihood_label in likelihood.items():
            term_document_vector = term_docs.getrow(i)

            counts = term_document_vector.data
            indices = term_document_vector.indices

            for count, index in zip(counts, indices):
                posterior[label] += np.log(likelihood_label[index]) * count
                # exp(-1000):exp(-999) will cause zero division error
                # however it equates to exp(0):exp(1)
                min_log_posterior = min(posterior.values())
                for label in posterior:
                    try:
                        posterior[label] = np.exp(posterior[label] - min_log_posterior)
                    except:
                        # if one's log value is excessively large, assign it infinity
                        posterior[label] = float('inf')

                    # normalize so that sum of posterior is 1
                    sum_posterior = sum(posterior.values())
                    for label in posterior:
                        if posterior[label] == float('inf'):
                            posterior[label] = 1.0
                        else:
                            posterior[label] /= sum_posterior
                    posteriors.append(posterior.copy())
    return posteriors      

In [41]:
emails_test = [
    '''Subject: flat screens
    hello,
    please call or contact regarding the other flat screens
    requested.
    trisha tlapek - eb 3132 b
    michael sergeev - eb 3132 a
    also the sun blocker that was taken away from eb 3131 a.
    trisha should two monitors also michael.
    thanks
    kevin moore''',
    '''Subject: having problems in bed? we can help!
    cialis allows men to enjoy a fully normal sex life without 
    having to plan the sexual act.
    if we let things terrify us, life will not be worth living
    brevity is the soul of lingerie.
    suspicion always haunts the guilty mind.'''
]

In [42]:
cleaned_test = clean_text(emails_test)

In [43]:
term_docs_test = cv.transform(cleaned_test)
posterior = get_posterior(term_docs_test, prior, likelihood)

In [44]:
print(posterior)

[{0: np.float64(1.0)}, {0: np.float64(1.0)}, {0: np.float64(1.0)}, {0: np.float64(1.0)}, {0: np.float64(1.0)}, {0: np.float64(1.0)}, {0: np.float64(1.0)}, {0: np.float64(1.0)}, {0: np.float64(1.0)}, {0: np.float64(1.0)}, {0: np.float64(1.0)}]


In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_train, X_test, y_train, y_test = train_test_split(cleaned_emails, labels, test_size = 0.33, random_state = 42)

In [47]:
len(X_train), len(X_test), len(y_train), len(y_test)

(1005, 495, 1005, 495)

In [50]:
term_docs_train = cv.fit_transform(X_train)

In [51]:
label_index = get_label_index(y_train)
prior = get_prior(label_index)
likelihood = get_likelihood(term_docs_train, label_index, smoothing)

In [52]:
term_docs_test = cv.transform(X_test)
posterior = get_posterior(term_docs_test, prior, likelihood)

In [53]:
correct = 0.0
for pred, actual in zip(posterior, y_test):
    if actual == 1:
        if pred[1] >= 0.5:
            correct += 1
        elif pred[0] > 0.5:
            correct += 1

In [54]:
print('The accuracy on {0} testing samples is: {1:.1f}%'.format(len(y_test), correct/len(y_test)*100))

The accuracy on 495 testing samples is: 0.0%


In [56]:
from sklearn.naive_bayes import MultinomialNB

In [57]:
clf = MultinomialNB(alpha = 1.0, fit_prior = True)

In [58]:
clf.fit(term_docs_train, y_train)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
Name,Type,Value
"class_count_ class_count_: ndarray of shape (n_classes,)Number of samples encountered for each class during fitting. Thisvalue is weighted by the sample weight when provided.","ndarray[float64](1,)",[1005.]
"class_log_prior_ class_log_prior_: ndarray of shape (n_classes,)Smoothed empirical log probability for each class.","ndarray[float64](1,)",[0.]
"classes_ classes_: ndarray of shape (n_classes,)Class labels known to the classifier","ndarray[int64](1,)",[0]
"feature_count_ feature_count_: ndarray of shape (n_classes, n_features)Number of samples encountered for each (class, feature)during fitting. This value is weighted by the sample weight whenprovided.","ndarray[float64](1, 500)","[[ 40., 40.,129.,...,110.,121., 33.]]"
"feature_log_prob_ feature_log_prob_: ndarray of shape (n_classes, n_features)Empirical log probability of featuresgiven a class, ``P(x_i|y)``.","ndarray[float64](1, 500)","[[-6.9 ,-6.9 ,-5.75,...,-5.91,-5.81,-7.09]]"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,500


In [59]:
prediction_prob = clf.predict_proba(term_docs_test)

In [60]:
prediction_prob[0:10]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [61]:
prediction = clf.predict(term_docs_test)
prediction[0:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [62]:
accuracy = clf.score(term_docs_test, y_test)
print('The accuracy using MultinomialNB is: {0:.1f}%'.format(accuracy*100))

The accuracy using MultinomialNB is: 100.0%
